### ISSUE TITLE
mobile slideshow & black blurb box - about page

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#36]
In mobile can slideshow be above the header and copy (blk box text section)?

**Comment by ebrelsford** [comment]
@a-murry Like this?

![selection_002](https://cloud.githubusercontent.com/assets/375002/25357220/02cae36e-290b-11e7-845c-efd0ff0a557c.png)

**Comment by a-murry** [comment]
that looks great to me!
