### ISSUE TITLE
archive theme/titles page - hyphenated titles

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#40]
Is there a way to avoid hyphenating titles? I'll post a couple screenshots and then list the stories it is happening for:

<img width="436" alt="screen shot 2017-04-22 at 1 47 58 pm" src="https://cloud.githubusercontent.com/assets/20864185/25306752/9dda9cf6-2761-11e7-8b41-b845cf521c0f.png">
<img width="830" alt="screen shot 2017-04-22 at 1 48 46 pm" src="https://cloud.githubusercontent.com/assets/20864185/25306753/9dea231a-2761-11e7-8b4c-0f77d4de18dc.png">

- Rehingold Brewery Closes: 600 Jobs and a Local Institution Lost ("THE PLACE LOOKS LIKE A GRAVEYARD NOW ... THIS DEVELOPMENT COULD SAVE US.")

- Serrani's Bakery (BREAKING BREAD: SERRANI'S SANITARY BAKERY)

- Interstate 280 cuts through the heart of the City of Orange (OVER 200 HOMES, BUSINESS, CHURCHES, AND COMMUNITY CENTERS WERE DEMOLISHED)

- Paul Robeson on Olcott Street (PAUL ROBESON GAVE A CONCERT IN ORANGE)

- Orange: a Just and Safe City ("HOW DO WE TAKE OUR FRUSTRATION AND LOVE FOR OUR CITY AND GET ACTIVE IN MAKING POSITIVE CHANGES IN OUR COMMUNITY?)

- Just and Safe Orange: a youth forum (FIELD NOTES FROM A YOUTH-LED COMMUNITY FORUM ON SAFETY)

- Bob Slater's "Outpost" program made a difference for kids in Orange (“MISFITS AND MALCONTENTS ARE THE HOPE OF THE WORLD”)

- Festival Latino de Orange, NJ September 24, 2016 (THE STREET PULSED WITH MUSIC AND PEOPLE, STROLLERS AND BLUE SALVADOR SPORTS SHIRTS)

**Comment by a-murry** [comment]
@ebrelsford I'm sorry if this is still in the works, but I'm still seeing hyphenation on these in Chrome (though it's fixed in my version of Safari)

**Comment by ebrelsford** [comment]
I don't see this happening in Chrome, can you post a screenshot?

**Comment by a-murry** [comment]
looks like it's not happening now! Sorry I jumped the gun on that one - it looks great!
