### ISSUE TITLE
image quote companion - chasm

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#50]
add mural photo as illustration stand in to accompany Mindy's quote at the head of the chasm parchment

images/RootShock_standin.jpg

**Comment by ebrelsford** [comment]
@a-murry Did you mean to upload a picture here? I don't see it if so.

**Comment by a-murry** [comment]
[images/RootShock_standin.jpg](url)

Yes, I had been trying to link to the image uploaded on github (name RootShock_standin.jpg)
