### ISSUE TITLE
quote attribution "-" - chasm

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#63]
no "-" in Mindy quote in Safari 9.1.3
<img width="1085" alt="screen shot 2017-04-22 at 3 08 38 pm" src="https://cloud.githubusercontent.com/assets/20864185/25307342/99552e6a-276d-11e7-93ee-ca62c5b4ecb5.png">

**Comment by ebrelsford** [comment]
@a-murry I've updated the attribution text, can you check to see if the dash is showing up now?

**Comment by a-murry** [comment]
I still don't see it, this is what I have now:
<img width="1101" alt="screen shot 2017-04-26 at 11 06 27 am" src="https://cloud.githubusercontent.com/assets/20864185/25441232/a09714c2-2a6f-11e7-98dc-c334c582fdcb.png">
