### ISSUE TITLE
artifact sheet arrows - theme specific?

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#64]
When I am in the individual artifact sheets and use the arrows to scroll through, it doesn't seem to be scrolling through sheets that are associated with the theme/title I had originally clicked. 

For example, when I click the "corner of good hope" theme, then the "HOW DO WE TAKE OUR FRUSTRATION AND LOVE FOR OUR CITY AND GET ACTIVE IN MAKING POSITIVE CHANGES IN OUR COMMUNITY?" artifact, then the right arrow, it takes me to “THE HAITIAN RELIGION IS VERY POWERFUL. YOU NEED TO ACKNOWLEDGE THE SPIRITS. THEY APPRECIATE BEING NOTICED.” - which is a part of the "orange is a crossroads" and "nostalgia and curiosity" themes.

**Comment by ebrelsford** [comment]
@a-murry I'm
